ACCUMULATE_STEPS: 2
AREA_THRESH: 100
AUG_MAX_SIZE: 1333
AUG_OVERFLOW_BBOX: false
AUG_RANDOM_CROP_MAX: 600
AUG_RANDOM_CROP_MIN: 384
AUG_RANDOM_RESIZE:
- 400
- 500
- 600
AUG_RANDOM_SHIFT_MAX_RATIO: 0.06
AUG_RESIZE_SCALES:
- 480
- 512
- 544
- 576
- 608
- 640
- 672
- 704
- 736
- 768
- 800
AUG_REVERSE_CLIP: 0.0
AUTO_MEMORY_OPTIMIZED_DETR_CRITERION: false
AVAILABLE_GPUS: 0
BACKBONE: resnet50
BATCH_SIZE: 1
CHECKPOINT_DETR_CRITERION: false
CLIP_MAX_NORM: 0.1
DATASETS:
- SportsMOT
DATASET_SPLITS:
- train
DATA_ROOT: /root/autodl-tmp/data
DETR_AUX_LOSS: true
DETR_BBOX_LOSS_COEF: 5.0
DETR_CHECKPOINT_FRAMES: 5
DETR_CLS_LOSS_COEF: 2.0
DETR_DEC_LAYERS: 6
DETR_DEC_N_POINTS: 4
DETR_DIM_FEEDFORWARD: 1024
DETR_DROPOUT: 0.0
DETR_ENC_LAYERS: 6
DETR_ENC_N_POINTS: 4
DETR_FOCAL_ALPHA: 0.25
DETR_FRAMEWORK: Deformable-DETR
DETR_GIOU_LOSS_COEF: 2.0
DETR_HIDDEN_DIM: 256
DETR_MASKS: false
DETR_NUM_FEATURE_LEVELS: 4
DETR_NUM_HEADS: 8
DETR_NUM_QUERIES: 300
DETR_NUM_TRAIN_FRAMES: 4
DETR_PE: sine
DETR_PRETRAIN: /root/autodl-tmp/MOTIP/r50_deformable_detr_coco_sportsmot.pth
DETR_TWO_STAGE: false
DETR_WITH_BOX_REFINE: true
DET_THRESH: 0.3
DEVICE: cuda
DILATION: false
EPOCHS: 18
EXP_GROUP: default
EXP_NAME: r50_deformable_detr_motip_sporttrack
EXP_OWNER: hellorpg
GIT_VERSION: null
ID_DECODER_LAYERS: 6
ID_LOSS_GPU_AVERAGE: true
ID_LOSS_WEIGHT: 1
ID_THRESH: 0.2
INFERENCE_CONFIG_PATH: null
INFERENCE_DATASET: SportsMOT
INFERENCE_ENSEMBLE: 0
INFERENCE_GROUP: null
INFERENCE_MAX_SIZE: 1333
INFERENCE_MODEL: null
INFERENCE_ONLY_DETR: false
INFERENCE_SPLIT: val
LR: 0.0001
LR_BACKBONE_NAMES:
- backbone.0
LR_BACKBONE_SCALE: 0.1
LR_LINEAR_PROJ_NAMES:
- reference_points
- sampling_offsets
LR_LINEAR_PROJ_SCALE: 0.05
LR_WARMUP_EPOCHS: 1
MAX_TEMPORAL_LENGTH: 40
MEMORY_OPTIMIZED_DETR_CRITERION: false
MODE: train
NEWBORN_THRESH: 0.6
NUM_CLASSES: 1
NUM_CPU_PER_GPU: null
NUM_ID_VOCABULARY: 50
NUM_WORKERS: 6
OUTPUTS_DIR: /root/autodl-tmp/MOTIP/output
OUTPUTS_PER_STEP: 100
PROJECT_NAME: MOTIP
RESUME_MODEL: null
RESUME_OPTIMIZER: true
RESUME_SCHEDULER: true
RESUME_STATES: true
SAMPLE_INTERVALS:
- 4
SAMPLE_LENGTHS:
- 40
SAMPLE_MODES:
- random_interval
SAMPLE_STEPS:
- 0
SAVE_CHECKPOINT_PER_EPOCH: 2
SCHEDULER_GAMMA: 0.1
SCHEDULER_MILESTONES:
- 10
- 16
SCHEDULER_TYPE: MultiStep
SEED: 42
SEQ_DECODER_CHECKPOINT: false
SEQ_DIM_FEEDFORWARD: 512
SEQ_HIDDEN_DIM: 256
SEQ_NUM_HEADS: 8
SUPER_CONFIG_PATH: ./configs/r50_deformable_detr_motip_dancetrack.yaml
TRAIN_STAGE: joint
TRAJ_DROP_RATIO: 0.5
TRAJ_SWITCH_RATIO: 0.3
USE_DISTRIBUTED: false
USE_TENSORBOARD: true
USE_WANDB: false
WEIGHT_DECAY: 0.0005
